latent_dim: 3
encoder:
    conv1:
      output_channels: 8
      kernel_shape: [4, 4]
      stride: 2
    conv2:
      output_channels: 16
      kernel_shape: [2, 2]
      stride: 1
    mlp:
      output_sizes:
      - 50
      - 50
      - ${latent_dim}
decoder:
  mlp:
    output_sizes: [50, 784]
  reshape:
    output_shape: [7, 7, 16]
  conv1:
    output_channels: 16
    kernel_shape: [2, 2]
    stride: 2
    output_shape: null #[14, 14]
  conv2:
    output_channels: 1
    kernel_shape: [4, 4]
    stride: 2
    output_shape: null #[28, 28]
