restore: null
restore_cfg: True

regularizer_coef: 0
desired_dim: 2
n_nearest: 128
n_training: 100
n_train_batches: 100
image_shape: [28, 28, 1]

defaults:
  - hydra: default
  - trainer: default
  - trainer/autoencoder: default
  - trainer/optimizer: default
  - _self_